import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import "./globals.css";
import {
  CustomProgressBar,
  Footer,
  Navbar,
  CustomLoadingBar,
  CustomAnimatedCursor,
} from "./_components";
import { Toaster } from "react-hot-toast";

const firaSans = Fira_Sans({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--firaSans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ali Usman | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${firaSans.className} mt-2`}>
        <CustomAnimatedCursor />
        <CustomLoadingBar />
        <CustomProgressBar />
        <Navbar />
        <main className="">{children}</main>
        <Footer />
        <Toaster
          toastOptions={{
            success: {
              iconTheme: {
                primary: "#FD853A",
                secondary: "white",
              },
            },
          }}
        />
      </body>
    </html>
  );
}
